var V = V || {};
V.Lang = V.Lang || {};
V.Lang.hr = {
    LBL_sto_trazite: "Što tražite",
    LBL_vinarija: "Vinarija",
    LBL_vinograd: "Vinograd",
    LBL_tvrtka: "Tvrtka",
    LBL_skladiste: "Skladište",
    URL_vinarija: "vinarija",
    URL_vinogradi: "vinogradi",
    URL_vinograd: "vinograd",
    URL_ulaz: "ulaz",
    URL_vino: "vino",
    URL_most: "most",
    URL_masulj: "masulj",
    URL_grozde: "grozde",
    URL_punjenje: "punjenje",
    URL_postavke: "postavke",
    URL_tvrtka: "tvrtka",
    URL_tankovi: "tankovi",
    URL_ljudi: "ljudi",
    URL_lokacije: "lokacije",
    URL_sorte: "sorte",
    URL_prerada: "prerada",
    URL_posuda: "posuda",
    URL_primka: "primka",
    URL_partneri: "partneri",
    URL_print: "print",

    //Reports
    LBL_pdf: "Preuzmi PDF",
    URL_ulaz_prema_partneru: "ulaz-prema-partneru",
    URL_ulaz_prema_sorti: "ulaz-prema-sorti",



    VRSTA_V: 'Vino',
    VRSTA_MO: 'Mošt',
    VRSTA_MA: 'Masulj',
    VRSTA_G: 'Grožđe',

    LBL_loading: ' Učitavanje...',


    LBL_tankovi: "Tankovi\nBa\u010dve",
    LBL_partneri: "Partneri",
    LBL_ljudi: "Ljudi",
    LBL_lokacija: "Lokacija",
    LBL_lokacije: "Lokacije",
    URL_skladiste: "skladiste",
    URL_enosredstva: "enosredstva",
    URL_repromaterijal: "gotovaroba",
    URL_gotovaroba: "gotova-roba",
    URL_katalog: "katalog",
    URL_izdavanje: "izdavanje",
    URL_pocetno: "pocetno-stanje",
    LBL_enosredstva: "Enolo\u0161ka sredstva",
    LBL_repromaterijal: "Repromaterijal",
    LBL_gotovaroba: "Gotova roba",
    LBL_katalog: "Katalog artikala",
    LBL_izdavanje: "Izdavanje Povrat",
    LBL_pocetno: "Po\u010detno stanje",
    /*
     * Vinogradi
     */
    LBL_vinogradi: "Vinogradi",
    M_vinogradi: "Vinogradi",
    M_sorte: "Sorte",
    LBL_sorte: "Sorte",
    LBL_novi: "Novi",
    LBL_obrisi: "Obri\u0161i",
    LBL_naziv: "Naziv",
    LBL_vrsta: "Vrsta",
    LBL_bijelo: "Bijelo",
    LBL_crno: "Crno",
    LBL_active: "Aktivno",
    LBL_spremi: "Spremi",
    LBL_oznaka: "Oznaka",
    LBL_arkod: "Arkod",
    LBL_jedinica: "Jedinica",
    LBL_komada: "Komada",
    LBL_dodajsortu: "Dodaj sortu",
    LBL_obrisisortu: "Obri\u0161i sortu",
    LBL_sorta: "Sorta",
    LBL_brojvinograda: "Broj vinograda",
    LBL_obrisisve: "Obri\u0161i sve...",
    LBL_polozaj: "Polo\u017eaj",
    LBL_povrsina: "Povr\u0161ina",
    MSG_obrisi_vinograde_potvrda: "Jeste li sigurni da \u017eelite obrisati sve vinograde? Samo one koji nisu kori\u0161teni.",
    LBL_partner: "Partner",
    LBL_add_variety: "Dodaj sortu",
    LBL_remove_variety: "Makni sortu",

    LBL_search: "Traži",
    LBL_uredi: "Uredi",
    LBL_komada_short: "kom",
    LBL_vino: "Vino",
    LBL_most: "Mo\u0161t",
    LBL_masulj: "Masulj",
    LBL_grozde: "Gro\u017e\u0111e",
    LBL_punjenje: "Punjenje",
    LBL_pakiranje: "Pakiranje",
    LBL_ulaz: "Ulaz",
    LBL_grozdemostvino: "Gro\u017e\u0111e - Mo\u0161t - Vino",
    LBL_pretok: "Pretok",
    LBL_tipizacija: "Tipizacija",
    LBL_brojPrimki: "Broj primki",
    LBL_kolicina: "Koli\u010dina",
    LBL_cijena: "Cijena",
    LBL_izvjestaj_partner: "Izvje\u0161taj prema partneru",
    LBL_izvjestaj_sorta: "Izvje\u0161taj prema sorti",
    LBL_randman: "Randman",
    LBL_ulaz_grozdemostvino: "Ulaz: gro\u017e\u0111e, mo\u0161t, vino",
    LBL_ispis: "Ispis",
    LBL_izdvajanje: "Izdvajanje",
    LBL_datum: "Datum",
    LBL_vrijeme: "Vrijeme",
    LBL_godina: "Godina berbe",
    LBL_napomena: "Napomena",
    LBL_kolicina_kg: "Kolicina (kg)",
    LBL_iznos: "Iznos",
    LBL_broj: "Broj",
    LBL_kalo_kg: "Kalo (kg)",
    LBL_kolicina_netto_kg: "Koli\u010dina netto (kg)",
    LBL_muljanje: "Muljanje",
    LBL_presanje: "Pre\u0161anje",
    LBL_sazetak: "Sa\u017eetak",
    LBL_izposude: "Iz posude",
    LBL_uposudu: "U posudu",
    LBL_kreiraj_lot: "Kreiraj lot",
    LBL_posuda: "Posuda",
    LBL_punjenja: "Punjenja",
    LBL_lot: "Lot",
    LBL_proizvod: "Proizvod",
    LBL_odaberi_proizvod: "Odaberi proizvod",
    LBL_odaberi_vino: "Odaberi vino",
    LBL_posuda_panel: "Posuda panel",
    LBL_kategorija_kakvoce: "Kategorija kakvo\u0107e",
    LBL_kolicina_proizvodnje: "Koli\u010dina proizvodnje",
    LBL_trosak_proizvodnje: "Tro\u0161ak proizvodnje",
    LBL_trosak_litra: "Tro\u0161ak po litri",
    FILE_izvjestaj_prerade: "izvjestaj_prerade.pdf",
    LBL_more: "U\u010ditaj jo\u0161",
    FILE_primka: "primka.pdf",
    LBL_date_format: "dd.MM.yyyy",
    LBL_zaprimanje: "Zaprimanje",
    MSG_da_li_ste_muljali_grozde: "Da li ste muljali ovo gro\u017e\u0111e?",
    MSG_korekcija_troska: "Korekcija tro\u0161ka zbog promjene cijena u primki",
    LBL_kolicina_l: "Koli\u010dina (L)",
    LBL_kalo_l: "Kalo (L)",
    LBL_kalo: "Kalo",
    LBL_analiza: "Analiza",
    LBL_sredstvo: "Sredstvo",
    LBL_start_fermentacije: "Start fermentacije",
    LBL_stop_fermentacije: "Stop fermentacije",
    LBL_nalog: "Nalog",
    LBL_oprema: "Tvrtka",
    LBL_prezimeime: "Prezime i ime",
    LBL_oib: "OIB",
    LBL_email: "E-mail",
    LBL_korisnickoime: "Korisni\u010dko ime",
    LBL_lozinka: "Lozinka",
    LBL_korisnik: "Korisnik",
    LBL_adresa: "Adresa",
    LBL_postbroj: "Po\u0161tanski broj",
    LBL_mjesto: "Mjesto",
    LBL_dobavljac: "Dobavlja\u010d",
    LBL_kupac: "Kupac",
    LBL_mibpg: "MIBPG",
    LBL_volumen: "Volumen",
    LBL_dodaj: "Dodaj",
    LBL_volumenposuda: "Volumen posuda",
    LBL_brojposuda: "Broj posuda",
    LBL_tankovibacve: "Tankovi i ba\u010dve",
    LBL_uvoz: "Uvoz...",
    LBL_change_password: "Promijeni lozinku",
    URL_lokacija: "lokacija",
    LBL_sekcije: "Sekcije",
    M_enosredstva: "Enolo\u0161ka sredstva",
    M_katalog: "Katalog artikala",
    M_izdavanje: "Izdavanje Povrat",
    M_repromaterijal: "Repromaterijal",
    M_gotovaroba: "Gotova roba",
    M_start: "Po\u010detno stanje",
    LBL_prerada: "Prerada",

    //Skladište
    LBL_novaprimka: "Nova primka",
    LBL_popisprimki: "Popis primki",
    LBL_sifra: "\u0160ifra",
    LBL_proizvodac: "Proizvo\u0111a\u010d",
    LBL_jm: "JM",
    LBL_stanje: "Stanje",
    LBL_doziranje: "Doziranje",
    LBL_jedinicadoziranje: "Jedinica za doziranje",
    LBL_izdatnica: "Izdatnica",
    LBL_ukupno: "Ukupno",
    LBL_stavke: "Stavke",
    LBL_povrat: "Povrat",
    LBL_isporuceno: "Isporu\u010deno",
    LBL_kreirajpovrat: "Kreiraj povrat",
    LBL_noviproizvod: "Novi proizvod",
    LBL_novopocetnostanje: "Novo po\u010detno stanje",
    LBL_artikl: "Artikl",
    LBL_artikli: "Artikli",
    LBL_primke: "Primke",
    LBL_jmstavke: "Jedinica mjere (stavke)",
    LBL_primka: "Primka",
    LBL_brojracuna: "Broj ra\u010duna/otpremnice",
    LBL_vino_most_masulj_grozde: "Vino, mo\u0161t, masulj, gro\u017e\u0111e",
    ERR_primka_jos_nije_spremljena: "Primka jo\u0161 nije spremljena_",
    LBL_total: "Ukupno",
    LBL_odustani: "Odustani",
    LBL_odabraniartikl: "Odabrani artikl",
    LBL_sirovina: "Sirovina",

    //Postavke
    LBL_dodaj_grupu: "Dodaj grupu",
    LBL_nova_grupa: "Nova grupa",
    LBL_obrisi_grupu: "Obri\u0161i grupu",
    LBL_grupa_za_punjenje: "Grupa za punjenje",
    LBL_nije_za_punjenje: "Nije za punjenje",
    LBL_odaberi_logo: "Odaberi logo",
    LBL_dozvole: "Dozvole",
    LBL_postavke: "Postavke",
    LBL_language: "Jezik",
    LBL_lang_en: "Engleski",
    LBL_lang_hr: "Hrvatski",
    LBL_general: "Općenito",
    LBL_grupe: "Grupe",
    LBL_parametri_analiza: "Parametri analiza",
    LBL_propisi: "Propisi",
    LBL_account: "Korisnički račun",
    LBL_grupa_grozde: "Grupa koja sadrži Grožđe",
    LBL_grupa_masulj: "Grupa koja sadrži Masulj",
    LBL_grupa_most: "Grupa koja sadrži Mošt",
    LBL_grupa_vino: "Grupa koja sadrži Vino",
    LBL_delete_local_db: "Obriši lokalnu bazu",
    LBL_container: "Container",
    LBL_podgrupa: "Podgrupa",
    LBL_odabrana_grupa: "Odabrana grupa",
    LBL_load_sampledata: "Učitaj sampledata",


};

