var V = V || {};
V.Lang = V.Lang || {};
V.Lang.en = {
    LBL_vino: "Wine",
    LBL_sto_trazite: "Search",
    LBL_vinarija: "Winery",
    LBL_vinograd: "Vineyards",
    LBL_tvrtka: "Company",
    LBL_skladiste: "Inventory",
    URL_vinarija: "winery",
    URL_vinogradi: "vineyards",
    URL_vinograd: "vineyard",
    URL_ulaz: "ulaz",
    URL_vino: "vino",
    URL_most: "most",
    URL_masulj: "masulj",
    URL_grozde: "grozde",
    URL_punjenje: "punjenje",
    URL_postavke: "settings",
    URL_tvrtka: "company",
    URL_tankovi: "tanks",
    URL_ljudi: "people",
    URL_sorte: "varieties",
    URL_lokacije: "locations",
    URL_prerada: "input",
    URL_posuda: "tank",
    URL_primka: "goods-receipt",
    URL_partneri: "partners",
    URL_print: "print",

    //Reports
    LBL_pdf: "Download PDF",
    URL_ulaz_prema_partneru: "input-by-partner",
    URL_ulaz_prema_sorti: "input-by-variety",

    VRSTA_V: 'Wine',
    VRSTA_MO: 'Must',
    VRSTA_MA: 'Crushed',
    VRSTA_G: 'Grape',

    LBL_loading: ' Loading...',

    LBL_tankovi: "Tanks\nBarrels",
    LBL_partneri: "Partners",
    LBL_ljudi: "People",
    LBL_lokacija: "Locations",
    LBL_lokacije: "Locations",
    URL_skladiste: "inventory",
    URL_enosredstva: "eno-supplements",
    URL_repromaterijal: "raw-material",
    URL_gotovaroba: "product-warehouse",
    URL_katalog: "product-catalog",
    URL_izdavanje: "issue-return",
    URL_pocetno: "initial-state",
    LBL_enosredstva: "Eno supplements",
    LBL_repromaterijal: "Raw material",
    LBL_gotovaroba: "Product warehouse",
    LBL_katalog: "Product catalog",
    LBL_izdavanje: "Issue Return",
    LBL_pocetno: "Initial state",

    /*
     * Vinogradi
     */
    LBL_vinogradi: "Vineyards",
    M_vinogradi: "Vineyards",
    M_sorte: "Varieties",
    LBL_sorte_izvjestaj: "Prerade prema sorti",
    LBL_novi: "New",
    LBL_obrisi: "Delete",
    LBL_naziv: "Name",
    LBL_vrsta: "Color",
    LBL_bijelo: "White",
    LBL_crno: "Red",
    LBL_active: "Active",
    LBL_spremi: "Save",
    LBL_oznaka: "Label",
    LBL_arkod: "Land id",
    LBL_jedinica: "Unit",
    LBL_komada: "Pieces",
    LBL_dodajsortu: "Add variety",
    LBL_obrisisortu: "Remove variety",
    LBL_sorta: "Variety",
    LBL_sorte: "Varieties",
    LBL_brojvinograda: "Nr. of vineyards",
    LBL_obrisisve: "Delete all...",
    LBL_polozaj: "Location",
    LBL_povrsina: "Area size",
    MSG_obrisi_vinograde_potvrda: "Are you sure you want to delete all vineyards? Only those that weren't benn used",
    LBL_partner: "Partner",
    LBL_add_variety: "Add variety",
    LBL_remove_variety: "Remove variety",

    LBL_search: "Search",
    LBL_uredi: "Edit",
    LBL_komada_short: "pcs",
    LBL_most: "Must",
    LBL_masulj: "Crushed grape",
    LBL_grozde: "Grapes",
    LBL_punjenje: "Filling",
    LBL_pakiranje: "Packaging",
    LBL_ulaz: "Input",
    LBL_grozdemostvino: "Grape - Must - Wine",
    LBL_pretok: "Wine transfer",
    LBL_tipizacija: "Blending",
    LBL_brojPrimki: "Nr. of receipts",
    LBL_izvjestaj_partner: "Receipts by partner",
    LBL_izvjestaj_sorta: "Receipts by variety",
    LBL_randman: "Yield",
    LBL_ulaz_grozdemostvino: "Input: grape, must, wine",
    LBL_ispis: "Print",
    LBL_izdvajanje: "Grape segregation",
    LBL_datum: "Date",
    LBL_vrijeme: "Time",
    LBL_kolicina: "Quantity",
    LBL_godina: "Vintage",
    LBL_napomena: "Note",
    LBL_kolicina_kg: "Quantity (kg)",
    LBL_cijena: "Price",
    LBL_iznos: "Amount",
    LBL_broj: "Nr_",
    LBL_kalo_kg: "Waste (kg)",
    LBL_kolicina_netto_kg: "Quantity net (kg)",
    LBL_muljanje: "Crushing",
    LBL_presanje: "Pressing",
    LBL_sazetak: "Summary",
    LBL_izposude: "From tank",
    LBL_uposudu: "To tank",
    LBL_kreiraj_lot: "Create lot nr.",
    LBL_posuda: "Tank",
    LBL_punjenja: "Fillings",
    LBL_lot: "Lot",
    LBL_proizvod: "Product",
    LBL_odaberi_proizvod: "Choose product",
    LBL_odaberi_vino: "Choose wine",
    LBL_posuda_panel: "Tank panel",
    LBL_kategorija_kakvoce: "Quality category",
    LBL_kolicina_proizvodnje: "Quantity produced",
    LBL_trosak_proizvodnje: "Cost of production",
    LBL_trosak_litra: "Cost per liter",
    FILE_izvjestaj_prerade: "report_processing_pdf",
    LBL_more: "More",
    FILE_primka: "receipt_pdf",
    LBL_date_format: "MM-dd-yyyy",
    LBL_zaprimanje: "Receiveing",
    MSG_da_li_ste_muljali_grozde: "Did you crush these grapes?",
    MSG_korekcija_troska: "Correction of cost beacuse receipt changed price",
    LBL_kolicina_l: "Quantity (L)",
    LBL_kalo_l: "Waste (L)",
    LBL_kalo: "Waste",
    LBL_analiza: "Analysis",
    LBL_sredstvo: "Supplement",
    LBL_start_fermentacije: "Fermentation start",
    LBL_stop_fermentacije: "Fermentation stop",
    LBL_nalog: "Order",
    LBL_oprema: "Company",
    LBL_prezimeime: "Full Name",
    LBL_oib: "Tax nr / SSN / VAT ID",
    LBL_email: "E-mail",
    LBL_korisnickoime: "Username",
    LBL_lozinka: "Password",
    LBL_korisnik: "User",
    LBL_adresa: "Address",
    LBL_postbroj: "Post nr.",
    LBL_mjesto: "City",
    LBL_dobavljac: "Supplier",
    LBL_kupac: "Customer",
    LBL_mibpg: "Land id",
    LBL_volumen: "Volume",
    LBL_dodaj: "Add",
    LBL_volumenposuda: "Tank volume",
    LBL_brojposuda: "Tank number",
    LBL_tankovibacve: "Tanks and barrels",
    LBL_uvoz: "Import...",
    LBL_change_password: "Change password",
    LBL_sekcije: "Sections",
    M_enosredstva: "Eno supplements",
    M_katalog: "Product catalog",
    M_izdavanje: "Issue Return",
    M_repromaterijal: "Raw material",
    M_gotovaroba: "Product warehouse",
    M_start: "Initial state",
    LBL_prerada: "Input",

    //Skladište
    LBL_novaprimka: "Goods receipt",
    LBL_popisprimki: "List of goods receipts",
    LBL_sifra: "SKU",
    LBL_proizvodac: "Producer",
    LBL_jm: "Unit",
    LBL_stanje: "Current state",
    LBL_doziranje: "Dosage",
    LBL_jedinicadoziranje: "Dosage unit",
    LBL_izdatnica: "Issue slip",
    LBL_ukupno: "Total",
    LBL_stavke: "Items",
    LBL_povrat: "Returns",
    LBL_isporuceno: "Delivered",
    LBL_kreirajpovrat: "Create return",
    LBL_noviproizvod: "New product",
    LBL_novopocetnostanje: "New initial state",
    LBL_artikl: "Product",
    LBL_artikli: "Products",
    LBL_primke: "Goods receipts",
    LBL_jmstavke: "Unit (item)",
    LBL_primka: "Goods receipt",
    LBL_brojracuna: "Invoice nr_",
    LBL_vino_most_masulj_grozde: "Wine, must,crushed, grape",
    ERR_primka_jos_nije_spremljena: "Receipt not saved",
    LBL_total: "Total",
    LBL_odustani: "Cancel",
    LBL_odabraniartikl: "Chosen product",
    LBL_sirovina: "Raw material",

//Postavke
    LBL_dodaj_grupu: "Add group",
    LBL_nova_grupa: "New group",
    LBL_obrisi_grupu: "Delete group",
    LBL_grupa_za_punjenje: "Filling group",
    LBL_nije_za_punjenje: "Not for filling",
    LBL_odaberi_logo: "Choose logo",
    LBL_dozvole: "Permitions",
    LBL_postavke: "Settings",
    LBL_language: "Language",
    LBL_lang_en: "English",
    LBL_lang_hr: "Croatian",
    LBL_general: "General",
    LBL_grupe: "Groups",
    LBL_parametri_analiza: "Analysis",
    LBL_propisi: "Regulations",
    LBL_account: "User account",
    LBL_grupa_grozde: "Group that contains Grape",
    LBL_grupa_masulj: "Grupa koja sadrži Crushed grape",
    LBL_grupa_most: "Grupa koja sadrži Must",
    LBL_grupa_vino: "Grupa koja sadrži Wine",
    LBL_delete_local_db: "Delete local database",
    LBL_container: "Container",
    LBL_podgrupa: "Subgroup",
    LBL_odabrana_grupa: "Selected group",
    LBL_load_sampledata: "Load sample data",


};
